name: Aghisna MIUI
on:
  workflow_dispatch:

jobs:
   release-project:
    name: Release Project
    runs-on: ubuntu-latest
    needs: build-project
    steps:
      - name: Create GitHub release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: ./*.zip
          asset_name: Aghisna${{ github.run_number }}.zip
          asset_content_type: application/zip

   build-project:
    runs-on: ubuntu-latest

    steps:
    - name: setting configurasi
      uses: actions/checkout@v3

    - name: setup environment
      run: |
          sudo apt-get update --fix-missing
          sudo apt-get install git make bc bison \
          openssl curl zip kmod cpio flex libelf-dev \
          libssl-dev libtfm-dev wget device-tree-compiler \
          ca-certificates python3 python2 binutils \
          binutils-aarch64-linux-gnu binutils-arm-linux-gnueabi \
          libghc-libyaml-dev libyaml-dev glibc-source \
    - name: ready compile...
      run: |
          curl https://raw.githubusercontent.com/RooGhz720/kernel_xiaomi_sm6150/aghisna-14/build.sh > build.sh
          chmod +x build.sh
          bash build.sh
      shell: bash
      env:
         CHATID: ${{ secrets.CHAT_ID }}
         API_BOT: ${{ secrets.BOT_API }}
         TYPE_KERNEL: ${{ secrets.EZA }}

